/** Independent rational cash flows; none of these results are generated by the implementation. */
export const FINANCIAL_FUNCTION_CORPUS = {
  PV: { formula: '=PV(0.5,2,-150)', expected: 166.666666666667 },
  FV: { formula: '=FV(0.5,2,-150)', expected: 375 },
  PMT: { formula: '=PMT(0.5,2,250)', expected: -225 },
  NPER: { formula: '=NPER(0.5,-150,0,375)', expected: 2 },
  IPMT: { formula: '=IPMT(0.5,1,2,250)', expected: -125 },
  PPMT: { formula: '=PPMT(0.5,1,2,250)', expected: -100 },
  ISPMT: { formula: '=ISPMT(0.5,0,2,250)', expected: -125 },
  EFFECT: { formula: '=EFFECT(0.2,2)', expected: 0.21 },
  NOMINAL: { formula: '=NOMINAL(0.21,2)', expected: 0.2 },
  SLN: { formula: '=SLN(1000,100,3)', expected: 300 },
  DOLLARDE: { formula: '=DOLLARDE(1.02,16)', expected: 1.125 },
  DOLLARFR: { formula: '=DOLLARFR(1.125,16)', expected: 1.02 },
} as const;
