// Generated by contracts/generate-contracts.mjs. Do not edit manually.
export type ProtectionAction = "edit-cell" | "format" | "insert-rows" | "insert-columns" | "delete-rows" | "delete-columns" | "sort" | "auto-filter" | "edit-objects" | "select-locked" | "select-unlocked";
export const PROTECTION_ACTION_ALLOW_FIELD = {
  "format": "formatCells",
  "insert-rows": "insertRows",
  "insert-columns": "insertColumns",
  "delete-rows": "deleteRows",
  "delete-columns": "deleteColumns",
  "sort": "sort",
  "auto-filter": "autoFilter",
  "edit-objects": "editObjects",
  "select-locked": "selectLocked",
  "select-unlocked": "selectUnlocked",
} as const;
