// Generated by contracts/generate-contracts.mjs. Do not edit manually.
package com.xc.luckysheet.server.contract;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum AccessPrincipalKind {
    SUBJECT("subject"),
    GROUP("group"),
    EVERYONE("everyone");

    private final String wireValue;

    AccessPrincipalKind(String wireValue) { this.wireValue = wireValue; }

    @JsonValue
    public String wireValue() { return wireValue; }

    @JsonCreator
    public static AccessPrincipalKind fromWireValue(String value) {
        for (AccessPrincipalKind candidate : values()) if (candidate.wireValue.equals(value)) return candidate;
        throw new IllegalArgumentException("Unsupported AccessPrincipalKind value: " + value);
    }
}
