// Generated by contracts/generate-contracts.mjs. Do not edit manually.
package com.xc.luckysheet.server.contract;

import java.util.Map;
import java.util.Set;

public final class GeneratedWorkbookContract {
    public static final String API_VERSION = "2026-08-24";
    public static final String SNAPSHOT_SCHEMA = "WorkbookSnapshot";
    public static final int SNAPSHOT_VERSION = 2;
    public static final int MAX_WORKBOOK_NAME_LENGTH = 255;
    public static final Set<String> ERROR_CODES = Set.of("UNAUTHENTICATED", "FORBIDDEN", "VALIDATION_ERROR", "NOT_FOUND", "CONFLICT", "WORKBOOK_TRASHED", "TIMEOUT", "SERVICE_UNAVAILABLE", "INTERNAL_ERROR");
    public static final Map<String, MutationCapability> MUTATIONS = Map.ofEntries(
        Map.entry("automation.recording.changed", new MutationCapability("transient", false)),
        Map.entry("pivot.chart.create", new MutationCapability("transient", false)),
        Map.entry("sheet.add", new MutationCapability("remote", true)),
        Map.entry("sheet.remove", new MutationCapability("remote", true)),
        Map.entry("sheet.rename", new MutationCapability("remote", true)),
        Map.entry("sheet.duplicated", new MutationCapability("remote", true)),
        Map.entry("sheet.restore", new MutationCapability("remote", true)),
        Map.entry("hyperlink.set", new MutationCapability("remote", true)),
        Map.entry("hyperlink.remove", new MutationCapability("remote", true)),
        Map.entry("query.load.workbook-table", new MutationCapability("local", false))
    );

    private GeneratedWorkbookContract() {}

    public static MutationCapability mutation(String id) {
        return MUTATIONS.get(id);
    }

    public record MutationCapability(String durability, boolean remote) {}
}
