// Generated by contracts/generate-contracts.mjs. Do not edit manually.
package com.xc.luckysheet.server.contract;
public final class GeneratedChartSubtypes {
    public static final java.util.Map<String, java.util.Set<String>> VALUES = java.util.Map.ofEntries(
        java.util.Map.entry("column", java.util.Set.of("clustered", "stacked", "percent-stacked", "three-dimensional", "three-dimensional-stacked", "three-dimensional-percent-stacked", "cone", "cone-stacked", "cone-percent-stacked", "cylinder", "cylinder-stacked", "cylinder-percent-stacked", "pyramid", "pyramid-stacked", "pyramid-percent-stacked")),
        java.util.Map.entry("bar", java.util.Set.of("clustered", "stacked", "percent-stacked", "three-dimensional", "three-dimensional-stacked", "three-dimensional-percent-stacked", "cone", "cone-stacked", "cone-percent-stacked", "cylinder", "cylinder-stacked", "cylinder-percent-stacked", "pyramid", "pyramid-stacked", "pyramid-percent-stacked")),
        java.util.Map.entry("line", java.util.Set.of("line", "line-markers", "stacked", "stacked-markers", "percent-stacked", "percent-stacked-markers", "three-dimensional")),
        java.util.Map.entry("area", java.util.Set.of("area", "stacked", "percent-stacked", "three-dimensional")),
        java.util.Map.entry("pie", java.util.Set.of("pie", "exploded-pie", "three-dimensional", "exploded-three-dimensional-pie", "pie-of-pie", "bar-of-pie")),
        java.util.Map.entry("doughnut", java.util.Set.of("doughnut", "exploded-doughnut")),
        java.util.Map.entry("scatter", java.util.Set.of("scatter-markers", "scatter-smooth-lines-markers", "scatter-smooth-lines", "scatter-straight-lines-markers", "scatter-straight-lines")),
        java.util.Map.entry("bubble", java.util.Set.of("bubble", "bubble-three-dimensional")),
        java.util.Map.entry("treemap", java.util.Set.of("treemap")),
        java.util.Map.entry("sunburst", java.util.Set.of("sunburst")),
        java.util.Map.entry("histogram", java.util.Set.of("histogram")),
        java.util.Map.entry("pareto", java.util.Set.of("pareto")),
        java.util.Map.entry("box-whisker", java.util.Set.of("box-whisker")),
        java.util.Map.entry("waterfall", java.util.Set.of("waterfall")),
        java.util.Map.entry("funnel", java.util.Set.of("funnel")),
        java.util.Map.entry("stock", java.util.Set.of("stock-high-low-close", "stock-open-high-low-close", "stock-volume-high-low-close", "stock-volume-open-high-low-close")),
        java.util.Map.entry("surface", java.util.Set.of("surface-three-dimensional", "surface-wireframe", "surface-contour", "surface-wireframe-contour")),
        java.util.Map.entry("radar", java.util.Set.of("radar", "radar-markers", "radar-filled")),
        java.util.Map.entry("map", java.util.Set.of("filled-map", "region-map")),
        java.util.Map.entry("combo", java.util.Set.of("clustered-column-line", "clustered-column-line-secondary", "stacked-area-clustered-column", "custom-combo"))
    );
    private GeneratedChartSubtypes() { }
}
