// Generated by contracts/generate-contracts.mjs. Do not edit manually.
package com.xc.luckysheet.server.contract;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum RangeAccessLevel {
    HIDDEN("hidden"),
    READ("read"),
    EDIT("edit");

    private final String wireValue;

    RangeAccessLevel(String wireValue) { this.wireValue = wireValue; }

    @JsonValue
    public String wireValue() { return wireValue; }

    @JsonCreator
    public static RangeAccessLevel fromWireValue(String value) {
        for (RangeAccessLevel candidate : values()) if (candidate.wireValue.equals(value)) return candidate;
        throw new IllegalArgumentException("Unsupported RangeAccessLevel value: " + value);
    }
}
