// Generated by contracts/generate-contracts.mjs. Do not edit manually.
package com.xc.luckysheet.server.contract;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum WorkbookRole {
    OWNER("owner"),
    EDITOR("editor"),
    COMMENTER("commenter"),
    VIEWER("viewer");

    private final String wireValue;

    WorkbookRole(String wireValue) { this.wireValue = wireValue; }

    public boolean includes(WorkbookRole required) { return ordinal() <= required.ordinal(); }

    @JsonValue
    public String wireValue() { return wireValue; }

    @JsonCreator
    public static WorkbookRole fromWireValue(String value) {
        for (WorkbookRole candidate : values()) if (candidate.wireValue.equals(value)) return candidate;
        throw new IllegalArgumentException("Unsupported WorkbookRole value: " + value);
    }
}
