export type RibbonAction =
  | 'undo' | 'redo' | 'copy' | 'cut' | 'paste'
  | 'bold' | 'italic' | 'underline' | 'strikethrough'
  | 'align-left' | 'align-center' | 'align-right'
  | 'v-align-top' | 'v-align-middle' | 'v-align-bottom'
  | 'wrap-text' | 'rotate' | 'font-family' | 'font-size'
  | 'merge-cells' | 'unmerge-cells' | 'textColor' | 'background'
  | 'numberFormat' | 'format-currency' | 'format-percent'
  | 'border-all' | 'border-outer' | 'border-none'
  | 'clear-range' | 'clear-formats' | 'autosum' | 'function-wizard'
  | 'sort-dialog' | 'sort-asc' | 'sort-desc'
  | 'insert-row' | 'insert-column' | 'delete-row' | 'delete-column'
  | 'hide-row' | 'hide-column' | 'unhide-all'
  | 'transpose' | 'flip-h' | 'flip-v' | 'split-column'
  | 'banded-toggle' | 'freeze-top-row' | 'freeze-first-col' | 'freeze-at-primary' | 'unfreeze'
  | 'filter-clear' | 'apply-filter-selection'
  | 'export-xlsx' | 'import-xlsx' | 'find-replace'
  | 'zoom-in' | 'zoom-out' | 'zoom-100'
  | 'open-chart' | 'open-pivot' | 'create-data-table'
  | 'open-shape' | 'open-sparkline' | 'open-conditional-format'
  | 'open-data-validation' | 'open-history' | 'open-print' | 'open-comments';
