// Generated by contracts/generate-contracts.mjs. Do not edit manually.
export const WORKBOOK_CONTRACT_API_VERSION = "2026-08-24" as const;
export const WORKBOOK_SNAPSHOT_SCHEMA = "WorkbookSnapshot" as const;
export const WORKBOOK_SNAPSHOT_VERSION = 5 as const;
export const MAX_WORKBOOK_NAME_LENGTH = 255 as const;
export const CONTRACT_ERROR_CODES = ["UNAUTHENTICATED", "FORBIDDEN", "VALIDATION_ERROR", "NOT_FOUND", "CONFLICT", "WORKBOOK_TRASHED", "TIMEOUT", "SERVICE_UNAVAILABLE", "INTERNAL_ERROR"] as const;
export type ContractErrorCode = typeof CONTRACT_ERROR_CODES[number];
export type MutationDurability = 'transient' | 'local' | 'remote';
export interface MutationCapability {
  durability: MutationDurability;
  remote: boolean;
  schema: string;
  minRole: 'owner' | 'editor' | 'commenter' | 'viewer';
  rebasePolicy: 'none' | 'range' | 'exact';
  javaReducer: boolean;
  replacement?: string;
}
export const MUTATION_CAPABILITIES = {
  "automation.recording.changed": { durability: "transient", remote: false, schema: "AutomationRecordingChanged", minRole: "editor", rebasePolicy: "none", javaReducer: false },
  "pivot.chart.create": { durability: "transient", remote: false, schema: "PivotChartCreate", minRole: "editor", rebasePolicy: "none", javaReducer: false, replacement: "drawing.add" },
  "sheet.add": { durability: "remote", remote: true, schema: "SheetAdd", minRole: "editor", rebasePolicy: "exact", javaReducer: true },
  "sheet.remove": { durability: "remote", remote: true, schema: "SheetRemove", minRole: "editor", rebasePolicy: "exact", javaReducer: true },
  "sheet.rename": { durability: "remote", remote: true, schema: "SheetRename", minRole: "editor", rebasePolicy: "exact", javaReducer: true },
  "sheet.duplicated": { durability: "remote", remote: true, schema: "SheetDuplicate", minRole: "editor", rebasePolicy: "exact", javaReducer: true },
  "sheet.restore": { durability: "remote", remote: true, schema: "SheetRestore", minRole: "editor", rebasePolicy: "exact", javaReducer: true },
  "hyperlink.set": { durability: "remote", remote: true, schema: "HyperlinkSet", minRole: "editor", rebasePolicy: "range", javaReducer: true },
  "hyperlink.remove": { durability: "remote", remote: true, schema: "HyperlinkRemove", minRole: "editor", rebasePolicy: "range", javaReducer: true },
  "column.defaultWidth.resize": { durability: "remote", remote: true, schema: "DefaultColumnWidthResizePx", minRole: "editor", rebasePolicy: "exact", javaReducer: true },
  "columns.visibility": { durability: "remote", remote: true, schema: "ColumnsVisibility", minRole: "editor", rebasePolicy: "range", javaReducer: true },
  "cellTemplate.set": { durability: "remote", remote: true, schema: "CellStyleTemplateSet", minRole: "editor", rebasePolicy: "exact", javaReducer: true },
  "cellTemplate.remove": { durability: "remote", remote: true, schema: "CellStyleTemplateRemove", minRole: "editor", rebasePolicy: "exact", javaReducer: true },
  "cell.editor.set": { durability: "remote", remote: true, schema: "CellEditorSet", minRole: "editor", rebasePolicy: "range", javaReducer: true },
  "tableSheet.update": { durability: "remote", remote: true, schema: "TableSheetDefinitionUpdate", minRole: "editor", rebasePolicy: "exact", javaReducer: true },
  "ganttSheet.update": { durability: "remote", remote: true, schema: "GanttSheetDefinitionUpdate", minRole: "editor", rebasePolicy: "exact", javaReducer: true },
  "query.load.workbook-table": { durability: "local", remote: false, schema: "QueryLoadWorkbookTable", minRole: "editor", rebasePolicy: "none", javaReducer: false },
} as const satisfies Record<string, MutationCapability>;
export function mutationCapability(id: string): MutationCapability | undefined {
  return MUTATION_CAPABILITIES[id as keyof typeof MUTATION_CAPABILITIES];
}
