// Generated by contracts/generate-contracts.mjs. Do not edit manually.
export const WORKBOOK_CONTRACT_API_VERSION = "2026-08-24" as const;
export const WORKBOOK_SNAPSHOT_SCHEMA = "WorkbookSnapshot" as const;
export const WORKBOOK_SNAPSHOT_VERSION = 2 as const;
export const MAX_WORKBOOK_NAME_LENGTH = 255 as const;
export const CONTRACT_ERROR_CODES = ["UNAUTHENTICATED", "FORBIDDEN", "VALIDATION_ERROR", "NOT_FOUND", "CONFLICT", "WORKBOOK_TRASHED", "TIMEOUT", "SERVICE_UNAVAILABLE", "INTERNAL_ERROR"] as const;
export type ContractErrorCode = typeof CONTRACT_ERROR_CODES[number];
export type MutationDurability = 'transient' | 'local' | 'remote';
export interface MutationCapability {
  durability: MutationDurability;
  remote: boolean;
  replacement?: string;
}
export const MUTATION_CAPABILITIES = {
  "automation.recording.changed": { durability: "transient", remote: false },
  "pivot.chart.create": { durability: "transient", remote: false, replacement: "drawing.add" },
  "sheet.add": { durability: "remote", remote: true },
  "sheet.remove": { durability: "remote", remote: true },
  "sheet.rename": { durability: "remote", remote: true },
  "sheet.duplicated": { durability: "remote", remote: true },
  "sheet.restore": { durability: "remote", remote: true },
  "hyperlink.set": { durability: "remote", remote: true },
  "hyperlink.remove": { durability: "remote", remote: true },
  "query.load.workbook-table": { durability: "local", remote: false },
} as const satisfies Record<string, MutationCapability>;
export function mutationCapability(id: string): MutationCapability | undefined {
  return MUTATION_CAPABILITIES[id as keyof typeof MUTATION_CAPABILITIES];
}
