export const defaultConfig = {
    defaultStore: {
        container: null,
        luckysheetfile: null,
        defaultcolumnNum: 60,
        defaultrowNum: 84,
        fullscreenmode: true,
        devicePixelRatio: 1,

        currentSheetIndex: 0,
        calculateSheetIndex: 0,
        flowdata: [],
        config: {},

        visibledatarow: [],
        visibledatacolumn: [],
        ch_width: 0,
        rh_height: 0,

        cellmainWidth: 0,
        cellmainHeight: 0,
        toolbarHeight: 0,
        infobarHeight: 0,
        calculatebarHeight: 0,
        rowHeaderWidth: 46,
        columnHeaderHeight: 20,
        cellMainSrollBarSize: 12,
        sheetBarHeight: 31,
        statisticBarHeight: 23,
        luckysheetTableContentHW: [0, 0],

        defaultcollen: 73,
        defaultrowlen: 19,

        jfcountfuncTimeout: null,
        jfautoscrollTimeout: null,

        luckysheet_select_status: false,
        luckysheet_select_save: [{ row: [0, 0], column: [0, 0] }],
        luckysheet_selection_range: [],

        luckysheet_copy_save: {},
        luckysheet_paste_iscut: false,

        filterchage: true,
        luckysheet_filter_save: { row: [], column: [] },

        luckysheet_sheet_move_status: false,
        luckysheet_sheet_move_data: [],
        luckysheet_scroll_status: false,

        luckysheetisrefreshdetail: true,
        luckysheetisrefreshtheme: true,
        luckysheetcurrentisPivotTable: false,

        luckysheet_rows_selected_status: false,
        luckysheet_cols_selected_status: false,
        luckysheet_rows_change_size: false,
        luckysheet_rows_change_size_start: [],
        luckysheet_cols_change_size: false,
        luckysheet_cols_change_size_start: [],
        luckysheet_cols_dbclick_timeout: null,
        luckysheet_cols_dbclick_times: 0,

        luckysheetCellUpdate: [],

        luckysheet_shiftpositon: null,

        iscopyself: true,

        orderbyindex: 0,

        luckysheet_model_move_state: false,
        luckysheet_model_xy: [0, 0],
        luckysheet_model_move_obj: null,

        luckysheet_cell_selected_move: false,
        luckysheet_cell_selected_move_index: [],

        luckysheet_cell_selected_extend: false,
        luckysheet_cell_selected_extend_index: [],
        luckysheet_cell_selected_extend_time: null,

        clearjfundo: true,
        jfredo: [],
        jfundo: [],
        lang: "en",
        createChart: "",
        highlightChart: "",
        zIndex: 15,
        chartparam: {
            luckysheetCurrentChart: null,
            luckysheetCurrentChartActive: false,
            luckysheetCurrentChartMove: null,
            luckysheetCurrentChartMoveTimeout: null,
            luckysheetCurrentChartMoveObj: null,
            luckysheetCurrentChartMoveXy: null,
            luckysheetCurrentChartMoveWinH: null,
            luckysheetCurrentChartMoveWinW: null,
            luckysheetCurrentChartResize: null,
            luckysheetCurrentChartResizeObj: null,
            luckysheetCurrentChartResizeXy: null,
            luckysheetCurrentChartResizeWinH: null,
            luckysheetCurrentChartResizeWinW: null,
            luckysheetInsertChartTosheetChange: true,
            luckysheetCurrentChartZIndexRank: 100,
            luckysheet_chart_redo_click: false,
            luckysheetCurrentChartMaxState: false,
            jfrefreshchartall: "",
            changeChartCellData: "",
            renderChart: "",
            getChartJson: "",
        },
        functionList: null,
        luckysheet_function: null,
        chart_selection: {},
        currentChart: "",
        scrollRefreshSwitch: true,

        measureTextCache: {},
        measureTextCellInfoCache: {},
        measureTextCacheTimeOut: null,
        cellOverflowMapCache: {},

        zoomRatio: 1,

        visibledatacolumn_unique: null,
        visibledatarow_unique: null,

        showGridLines: true,

        toobarObject: {},
        inlineStringEditCache: null,
        inlineStringEditRange: null,

        fontList: [],

        currentSheetView: "viewNormal",
        drawDirtyRect: null,
        drawViewportRect: null,
    },
    defaultFormula: {
        searchFunctionCell: null,
        functionlistPosition: {},
        rangechangeindex: null,
        rangestart: false,
        rangetosheet: null,
        rangeSetValueTo: null,
        func_selectedrange: {},
        rangedrag_column_start: false,
        rangedrag_row_start: false,
        rangeResizeObj: null,
        rangeResize: null,
        rangeResizeIndex: null,
        rangeResizexy: null,
        rangeResizeWinH: null,
        rangeResizeWinW: null,
        rangeResizeTo: null,
        rangeMovexy: null,
        rangeMove: false,
        rangeMoveObj: null,
        rangeMoveIndex: null,
        rangeMoveRangedata: null,
        functionHTMLIndex: 0,
        functionRangeIndex: null,
        execvertex: {},
        execFunctionGroupData: null,
        execFunctionExist: null,
        formulaContainSheetList: {},
        cellTextToIndexList: {},
        isFunctionRangeSave: false,
        formulaContainCellList: {},
        execFunctionGlobalData: {},
        groupValuesRefreshData: [],
        functionResizeData: {},
        functionResizeStatus: false,
        functionResizeTimeout: null,
        data_parm_index: 0,
    },
    defaultSheet: {
        sheetMaxIndex: 0,
        nulldata: null,
        mergeCalculationSheet: {},
        checkLoadSheetIndexToDataIndex: {},
        CacheNotLoadControll: [],
    },
    defaultPivotTable: {
        pivotDatas: null,
        pivotSheetIndex: 0,
        pivotDataSheetIndex: 0,
        celldata: null,
        origindata: null,
        pivot_data_type: {},
        pivot_select_save: null,
        column: null,
        row: null,
        values: null,
        filter: null,
        showType: null,
        rowhidden: null,
        selected: null,
        caljs: null,
        initial: true,
        filterparm: null,
        luckysheet_pivotTable_select_state: false,
        jgridCurrentPivotInput: null,
        movestate: false,
        moveitemposition: [],
        movesave: {},
        drawPivotTable: true,
        pivotTableBoundary: [12, 6],
    },
    defaultImage: {
        imgItem: {
            type: "3",
            src: "",
            originWidth: null,
            originHeight: null,
            default: {
                width: null,
                height: null,
                left: null,
                top: null,
            },
            crop: {
                width: null,
                height: null,
                offsetLeft: 0,
                offsetTop: 0,
            },
            isFixedPos: false,
            fixedLeft: null,
            fixedTop: null,
            border: {
                width: 0,
                radius: 0,
                style: "solid",
                color: "#000",
            },
        },
        images: null,
        currentImgId: null,
        currentWinW: null,
        currentWinH: null,
        resize: null,
        resizeXY: null,
        move: false,
        moveXY: null,
        cropChange: null,
        cropChangeXY: null,
        cropChangeObj: null,
        copyImgItemObj: null,
    },
    defaultDataVerification: {
        defaultItem: {
            type: "dropdown",
            type2: null,
            value1: "",
            value2: "",
            checked: false,
            remote: false,
            prohibitInput: false,
            hintShow: false,
            hintText: "",
        },
        curItem: null,
        dataVerification: null,
        selectRange: [],
        selectStatus: false,
    },
    defaultFreezen: {
        initialHorizontal: true,
        initialVertical: true,
        horizontalmovestate: false,
        horizontalmoveposition: null,
        verticalmovestate: false,
        verticalmoveposition: null,
        windowHeight: null,
        windowWidth: null,
        freezenhorizontaldata: null,
        freezenverticaldata: null,
        freezenRealFirstRowColumn: true,
    },
    defaultServer: {
        gridKey: null,
        loadUrl: null,
        updateUrl: null,
        updateImageUrl: null,
        title: null,
        loadSheetUrl: null,
        retryTimer: null,
        allowUpdate: false,
        collabSeq: 0,
        lastAckVer: 0,
        lastRemoteVer: 0,
        cellClock: {},
        outboundQueue: [],
        outboundQueueLimit: 200,
        intentionalClose: false,
        reconnectTimer: null,
        reconnectAttempt: 0,
        maxReconnectAttempts: 20,
        reconnectBaseDelay: 1000,
        onlineListenerBound: false,
        websocket: null,
    },
};

export default defaultConfig;
