// Generated by contracts/generate-contracts.mjs. Do not edit manually.
export const NATIVE_DOCUMENT_STRUCTURAL_CAPABILITY_POLICY = {
  "policyRevision": 1,
  "features": {
    "unknownWorksheetNode": "unknown-worksheet-node",
    "unknownWorkbookNode": "unknown-workbook-node",
    "unknownExtension": "unknown-extension",
    "extendedValidation": "extended-validation",
    "extendedConditionalFormat": "extended-conditional-format",
    "preservedNativeChart": "preserved-native-chart"
  },
  "blockingFeatures": [
    "unknown-worksheet-node",
    "unknown-workbook-node",
    "unknown-extension",
    "extended-validation",
    "extended-conditional-format",
    "preserved-native-chart"
  ],
  "worksheet": {
    "rootElement": "worksheet",
    "rootAttributes": [],
    "singletonNodes": [
      "sheetPr",
      "dimension",
      "sheetViews",
      "sheetFormatPr",
      "sheetCalcPr",
      "phoneticPr",
      "extLst",
      "drawing",
      "legacyDrawing",
      "sheetData",
      "cols",
      "mergeCells",
      "hyperlinks",
      "dataValidations",
      "autoFilter",
      "sheetProtection",
      "printOptions",
      "pageMargins",
      "pageSetup",
      "headerFooter",
      "rowBreaks",
      "colBreaks",
      "tableParts",
      "pivotTableParts"
    ],
    "extensionListNode": "extLst",
    "extensionNode": "ext",
    "featureNodes": {
      "sheetData": "cells",
      "cols": "styles",
      "mergeCells": "merges",
      "hyperlinks": "hyperlinks",
      "conditionalFormatting": "conditional-format",
      "dataValidations": "validation",
      "autoFilter": "filters",
      "sheetProtection": "protection",
      "printOptions": "print-setup",
      "pageMargins": "print-setup",
      "pageSetup": "print-setup",
      "headerFooter": "print-setup",
      "rowBreaks": "print-setup",
      "colBreaks": "print-setup",
      "tableParts": "tables",
      "pivotTableParts": "pivot"
    },
    "structuralNodes": [
      "sheetPr",
      "dimension",
      "sheetViews",
      "sheetFormatPr",
      "extLst",
      "drawing"
    ],
    "nodes": {
      "sheetPr": {
        "attributes": [],
        "children": {
          "tabColor": {
            "attributes": [
              "rgb"
            ],
            "mustBeLeaf": true,
            "mustHaveWhitespaceText": true,
            "supportedValues": {}
          },
          "outlinePr": {
            "attributes": [
              "summaryBelow",
              "summaryRight"
            ],
            "mustBeLeaf": true,
            "mustHaveWhitespaceText": true,
            "supportedValues": {
              "summaryBelow": [
                "1",
                "true"
              ],
              "summaryRight": [
                "1",
                "true"
              ]
            }
          }
        }
      },
      "sheetFormatPr": {
        "attributes": [
          "baseColWidth",
          "defaultColWidth",
          "defaultRowHeight"
        ],
        "mustBeLeaf": true,
        "mustHaveWhitespaceText": true,
        "positiveNumericAttributes": [
          "baseColWidth",
          "defaultColWidth",
          "defaultRowHeight"
        ]
      }
    },
    "extendedRuleNodes": {
      "validation": [
        "dataValidations",
        "dataValidation"
      ],
      "conditionalFormat": [
        "conditionalFormatting"
      ]
    },
    "extensionUris": {
      "sparklineGroups": "{05C60535-1F16-4FD2-B633-F4F36F0B64E0}",
      "slicerList": "{A8765BA9-456A-4DAB-B4F3-ACF838C121DE}",
      "timelineRefs": "{7E03D99C-DC04-49D9-9315-930204A7B6E9}"
    },
    "controlExtensions": [
      {
        "uriKey": "slicerList",
        "kind": "slicer",
        "containerNode": "slicerList",
        "itemNode": "slicer",
        "relationshipField": "relationshipId"
      },
      {
        "uriKey": "timelineRefs",
        "kind": "timeline",
        "containerNode": "timelineRefs",
        "itemNode": "timelineRef",
        "relationshipField": "relationshipId"
      }
    ],
    "sparkline": {
      "containerNode": "sparklineGroups",
      "groupNode": "sparklineGroup",
      "collectionNode": "sparklines",
      "itemNode": "sparkline",
      "formulaNode": "f",
      "cellReferenceNode": "sqref",
      "groupAttributes": [
        "type",
        "lineWeight",
        "dateAxis",
        "markers",
        "high",
        "low",
        "first",
        "last",
        "negative",
        "displayXAxis",
        "rightToLeft",
        "displayHidden",
        "displayEmptyCellsAs",
        "manualMin",
        "manualMax",
        "colorSeries",
        "colorNegative",
        "colorAxis",
        "colorMarkers",
        "colorFirst",
        "colorLast",
        "colorHigh",
        "colorLow"
      ],
      "colorNodes": [
        "colorSeries",
        "colorNegative",
        "colorAxis",
        "colorMarkers",
        "colorFirst",
        "colorLast",
        "colorHigh",
        "colorLow"
      ],
      "types": [
        "line",
        "column",
        "win-loss"
      ],
      "booleanAttributes": [
        "dateAxis",
        "markers",
        "high",
        "low",
        "first",
        "last",
        "negative",
        "displayXAxis",
        "rightToLeft",
        "displayHidden"
      ],
      "numericAttributes": [
        "lineWeight",
        "manualMin",
        "manualMax"
      ],
      "colorAttributes": [
        "colorSeries",
        "colorNegative",
        "colorAxis",
        "colorMarkers",
        "colorFirst",
        "colorLast",
        "colorHigh",
        "colorLow"
      ],
      "cellColorAttributes": [
        "rgb",
        "val"
      ]
    }
  },
  "workbook": {
    "rootElement": "workbook",
    "extensionListNode": "extLst",
    "extensionNode": "ext",
    "singletonNodes": [
      "workbookPr",
      "sheets",
      "definedNames",
      "pivotCaches",
      "bookViews",
      "calcPr",
      "fileVersion",
      "fileSharing",
      "workbookProtection",
      "extLst"
    ],
    "rootNodes": [
      "workbookPr",
      "sheets",
      "definedNames",
      "pivotCaches",
      "bookViews",
      "calcPr",
      "fileVersion",
      "fileSharing",
      "workbookProtection",
      "extLst"
    ],
    "rootAttributes": [],
    "nodes": {
      "workbookPr": {
        "attributes": [
          "date1904"
        ],
        "mustBeLeaf": true,
        "mustHaveWhitespaceText": true
      },
      "pivotCaches": {
        "attributes": [
          "count"
        ],
        "mustHaveWhitespaceText": true,
        "child": {
          "name": "pivotCache",
          "attributes": [
            "cacheId",
            "r:id",
            "id"
          ],
          "mustBeLeaf": true,
          "mustHaveWhitespaceText": true
        }
      },
      "sheets": {
        "attributes": [],
        "mustHaveWhitespaceText": true,
        "child": {
          "name": "sheet",
          "attributes": [
            "name",
            "sheetId",
            "r:id",
            "id",
            "state"
          ],
          "mustBeLeaf": true,
          "mustHaveWhitespaceText": true,
          "stateValues": [
            "visible",
            "hidden"
          ]
        }
      },
      "definedNames": {
        "attributes": [],
        "mustHaveWhitespaceText": true,
        "child": {
          "name": "definedName",
          "attributes": [
            "name",
            "localSheetId",
            "hidden"
          ],
          "mustBeLeaf": true
        }
      }
    },
    "extensionUris": {
      "slicerCaches": "{BBE1A952-AA13-448E-AADC-164F8A28A991}",
      "timelineCacheRefs": "{D0CA8CA8-9F24-4464-BF8E-62219DCF47F9}"
    },
    "controlExtensions": [
      {
        "uriKey": "slicerCaches",
        "kind": "slicer",
        "containerNode": "slicerCaches",
        "itemNode": "slicerCache",
        "relationshipField": "cacheRelationshipId"
      },
      {
        "uriKey": "timelineCacheRefs",
        "kind": "timeline",
        "containerNode": "timelineCacheRefs",
        "itemNode": "timelineCacheRef",
        "relationshipField": "cacheRelationshipId"
      }
    ]
  },
  "controlExtensionAttributes": [
    "uri"
  ],
  "controlReferenceAttributes": [
    "r:id"
  ]
} as const;
