import type { Locale } from '../../i18n';

const messages = {
  'zh-CN': {
    createTitle: '创建数据透视表', chooseData: '请选择要分析的数据', chooseLocation: '选择放置数据透视表的位置', newWorksheet: '新工作表', existingWorksheet: '现有工作表', confirm: '确定', cancel: '取消',
    fieldsTitle: '数据透视表字段', addFields: '选择要添加到报表的字段', search: '搜索', total: '合计', dragFields: '字段区域', dragFieldsHere: '将字段拖到此处', filters: '筛选', columns: '列', rows: '行', values: '值', delayUpdate: '延迟布局更新', update: '更新', view: '视图', fieldPaneLayout: '字段列表布局', stacked: '字段与区域堆叠', sideBySide: '字段与区域并排', areas2x2: '区域 2×2', areas1x4: '区域 1×4', fieldsOnly: '仅字段', areasOnly: '仅区域', paneResize: '调整字段和区域大小', fieldSettings: '字段设置', subtotal: '分类汇总', subtotalAutomatic: '自动', subtotalNone: '无', subtotalCustom: '自定义', subtotalLocation: '分类汇总位置', subtotalTop: '组顶部', subtotalBottom: '组底部', subtotalOff: '关闭', formatAndOptions: '格式与选项', assignTo: '添加到', selectedFields: '已用 {selected}/{total}', dragOrChoose: '拖动字段，或使用字段菜单添加',
    noFields: '没有可用字段', noMatches: '没有匹配字段', loading: '正在准备数据透视表字段。', error: '数据透视表字段加载失败。', empty: '请选择一个数据透视表以配置字段。', close: '关闭数据透视表字段', source: '数据源', target: '目标', configure: '配置', pivotControls: '透视表控件', refresh: '刷新', compact: '紧凑', outline: '大纲', tabular: '表格', controlField: '控件字段', slicer: '切片器', timeline: '时间线', pivotChart: '数据透视图',
    expandFields: '展开字段', collapseFields: '折叠字段', fieldMenu: '字段菜单', moveUp: '上移', moveDown: '下移', remove: '删除', advancedFields: '高级数据透视表字段',
    valueSettings: '值字段设置', summaryFunction: '汇总方式', displayName: '自定义名称', displayNamePlaceholder: '输入自定义名称', numberFormat: '数字格式', numberFormatPlaceholder: '数字格式，例如 #,##0.00', showValueAs: '值显示方式', baseField: '基本字段', baseItem: '基本项',
    normal: '无计算', grandPercent: '总计的百分比', rowPercent: '行汇总的百分比', columnPercent: '列汇总的百分比', parentPercent: '父级汇总的百分比', differenceFrom: '差异', percentDifferenceFrom: '差异百分比', runningTotal: '按某一字段汇总', percentRunningTotal: '按某一字段汇总的百分比', rank: '升序/降序排列', index: '指数',
    sortBy: '排序', ascending: '升序', descending: '降序', valueAscending: '按值升序', valueDescending: '按值降序', clearSort: '清除排序', filterValues: '筛选值', filterMode: '筛选模式', showAll: '显示全部', includeSelected: '仅包含所选项', excludeSelected: '排除所选项',
    groupBy: '分组', years: '年', quarters: '季度', months: '月', weeks: '周', days: '日', clearGroup: '取消组合', groupNumbers: '数字分组', by10: '间隔 10', by100: '间隔 100', groupAll: '组合全部值', groupOne: '组 1', groupStart: '起始于', groupEnd: '结束于', groupInterval: '间隔', weekStarts: '每周开始于', sunday: '星期日', monday: '星期一', saturday: '星期六', applyGroup: '应用分组', manualGrouping: '手动分组', selectItemsToGroup: '选择两个或更多项目来创建分组', groupName: '分组名称', createGroup: '创建分组', ungroup: '取消此组',
    calculatedFieldsItems: '计算字段和计算项', calculatedField: '计算字段', calculatedItem: '计算项', calculatedName: '名称', calculatedFormula: '公式', calculatedItemName: '计算项名称', add: '添加',
    slicerTitle: '切片器', clearFilter: '清除筛选', selectAll: '全选', searchItems: '搜索项目', timelineTitle: '时间线', timelineStart: '开始日期', timelineEnd: '结束日期', clearTimeline: '清除时间线', configurationActions: '数据透视表配置操作', pivotStyle: '数据透视表样式', styleLight: '浅色 16', styleMedium: '中等 4', styleDark: '深色 2', rowHeaders: '行标题', columnHeaders: '列标题', bandedRows: '带状行', bandedColumns: '带状列', lastColumn: '最后一列', expandField: '展开字段', collapseField: '折叠字段', showButtons: '显示 +/- 按钮', hideButtons: '隐藏 +/- 按钮',
    sum: '求和', count: '计数', countNumbers: '数值计数', average: '平均值', min: '最小值', max: '最大值', product: '乘积', stdev: '标准偏差', stdevp: '总体标准偏差', variance: '方差', variancep: '总体方差', distinctCount: '非重复值计数', rowLabels: '行标签', grandTotal: '总计', loadingPivot: '正在加载数据透视表', pivotCollision: '数据透视表无法展开', pivotRefreshFailed: '数据透视表刷新失败', pivotRefreshRequired: '数据透视表需要刷新', invalidSource: '请选择有效的数据透视表数据源', invalidDestination: '请输入有效的放置位置，例如 A1', layoutUpdated: '数据透视表布局已更新', filterUpdated: '数据透视表筛选已更新', currentRegion: '当前区域', tableSource: '表格', namedRange: '定义名称', allItems: '全部', selectedItems: '已选择 {count} 项', excludedItems: '排除 {count} 项', topItemsSummary: '{direction} {count} 项（依据 {field}）', labelFilter: '标签筛选', dateFilter: '日期筛选', valueFilter: '值筛选', beginsWith: '开头是', notBeginsWith: '开头不是', endsWith: '结尾是', notEndsWith: '结尾不是', contains: '包含', notContains: '不包含', between: '介于', notBetween: '不介于', before: '早于', after: '晚于', top: '前', bottom: '后', dynamicDate: '动态日期', today: '今天', yesterday: '昨天', tomorrow: '明天', thisWeek: '本周', lastWeek: '上周', nextWeek: '下周', thisMonth: '本月', lastMonth: '上月', nextMonth: '下月', thisQuarter: '本季度', lastQuarter: '上季度', nextQuarter: '下季度', thisYear: '今年', lastYear: '去年', nextYear: '明年', yearToDate: '今年迄今', otherSortOptions: '其他排序选项…', clearFieldFilter: '从“{field}”中清除筛选', sortField: '排序依据', pivotOptions: '数据透视表选项', layoutFormat: '布局和格式', displayOptions: '显示选项', fillEmptyCells: '填充空单元格', emptyCellText: '空单元格显示', showErrorValues: '显示错误值', errorCellText: '错误值显示', showFieldHeaders: '显示字段标题和筛选按钮', autoFitColumns: '更新时自动调整列宽', preserveFormatting: '更新时保留单元格格式',
    topBottomFilter: '前/后筛选', topBottomMode: '筛选依据', items: '项目', percent: '百分比', threshold: '阈值', topBottomSummary: '{direction} {mode} {threshold}（依据 {field}）',
    timelineLevel: '时间级别', timelineStyle: '时间线样式', timelineCaption: '时间线标题', timelinePrevious: '上一时间段', timelineNext: '下一时间段', timelineAllPeriods: '全部时间段', timelineHeader: '显示标题', timelineSelection: '显示选择范围', reportConnections: '报表连接', noCompatiblePivots: '没有兼容的数据透视表',
  },
  'en-US': {
    createTitle: 'Create PivotTable', chooseData: 'Choose the data that you want to analyze', chooseLocation: 'Choose where you want the PivotTable to be placed', newWorksheet: 'New Worksheet', existingWorksheet: 'Existing Worksheet', confirm: 'OK', cancel: 'Cancel',
    fieldsTitle: 'PivotTable Fields', addFields: 'Choose fields to add to report', search: 'Search', total: 'Total', dragFields: 'Field areas', dragFieldsHere: 'Drag fields here', filters: 'Filters', columns: 'Columns', rows: 'Rows', values: 'Values', delayUpdate: 'Defer Layout Update', update: 'Update', view: 'View', fieldPaneLayout: 'Field List layout', stacked: 'Fields and Areas stacked', sideBySide: 'Fields and Areas side by side', areas2x2: 'Areas 2×2', areas1x4: 'Areas 1×4', fieldsOnly: 'Fields only', areasOnly: 'Areas only', paneResize: 'Resize fields and areas', fieldSettings: 'Field Settings', subtotal: 'Subtotals', subtotalAutomatic: 'Automatic', subtotalNone: 'None', subtotalCustom: 'Custom', subtotalLocation: 'Subtotal location', subtotalTop: 'Top of group', subtotalBottom: 'Bottom of group', subtotalOff: 'Off', formatAndOptions: 'Format & options', assignTo: 'Add to', selectedFields: '{selected}/{total} used', dragOrChoose: 'Drag fields or use the field menu',
    noFields: 'No fields are available', noMatches: 'No matching fields', loading: 'Preparing PivotTable fields.', error: 'PivotTable fields could not be loaded.', empty: 'Select a PivotTable to configure its fields.', close: 'Close PivotTable fields', source: 'Source', target: 'Target', configure: 'Configure', pivotControls: 'Pivot controls', refresh: 'Refresh', compact: 'Compact', outline: 'Outline', tabular: 'Tabular', controlField: 'Control field', slicer: 'Slicer', timeline: 'Timeline', pivotChart: 'Pivot Chart',
    expandFields: 'Expand fields', collapseFields: 'Collapse fields', fieldMenu: 'Field menu', moveUp: 'Move up', moveDown: 'Move down', remove: 'Remove', advancedFields: 'Advanced PivotTable fields',
    valueSettings: 'Value Field Settings', summaryFunction: 'Summarize Values By', displayName: 'Custom Name', displayNamePlaceholder: 'Custom display name', numberFormat: 'Number Format', numberFormatPlaceholder: 'Number format, e.g. #,##0.00', showValueAs: 'Show Values As', baseField: 'Base field', baseItem: 'Base item',
    normal: 'No Calculation', grandPercent: '% of Grand Total', rowPercent: '% of Row Total', columnPercent: '% of Column Total', parentPercent: '% of Parent Total', differenceFrom: 'Difference From', percentDifferenceFrom: '% Difference From', runningTotal: 'Running Total In', percentRunningTotal: '% Running Total In', rank: 'Rank', index: 'Index',
    sortBy: 'Sort', ascending: 'Ascending', descending: 'Descending', valueAscending: 'Value ascending', valueDescending: 'Value descending', clearSort: 'Clear sort', filterValues: 'Filter values', filterMode: 'Filter mode', showAll: 'Show all', includeSelected: 'Include selected', excludeSelected: 'Exclude selected',
    groupBy: 'Group by', years: 'Years', quarters: 'Quarters', months: 'Months', weeks: 'Weeks', days: 'Days', clearGroup: 'Ungroup', groupNumbers: 'Group numbers', by10: 'By 10', by100: 'By 100', groupAll: 'Group all values', groupOne: 'Group 1', groupStart: 'Starting at', groupEnd: 'Ending at', groupInterval: 'By', weekStarts: 'Week starts on', sunday: 'Sunday', monday: 'Monday', saturday: 'Saturday', applyGroup: 'Apply grouping', manualGrouping: 'Manual grouping', selectItemsToGroup: 'Select two or more items to create a group', groupName: 'Group name', createGroup: 'Create group', ungroup: 'Ungroup',
    calculatedFieldsItems: 'Calculated Fields / Items', calculatedField: 'Calculated field', calculatedItem: 'Calculated item', calculatedName: 'Name', calculatedFormula: 'Formula', calculatedItemName: 'Item name', add: 'Add',
    slicerTitle: 'Slicer', clearFilter: 'Clear filter', selectAll: 'Select all', searchItems: 'Search items', timelineTitle: 'Timeline', timelineStart: 'Timeline start', timelineEnd: 'Timeline end', clearTimeline: 'Clear timeline', configurationActions: 'Pivot configuration actions', pivotStyle: 'PivotTable Style', styleLight: 'Light 16', styleMedium: 'Medium 4', styleDark: 'Dark 2', rowHeaders: 'Row Headers', columnHeaders: 'Column Headers', bandedRows: 'Banded Rows', bandedColumns: 'Banded Columns', lastColumn: 'Last Column', expandField: 'Expand Field', collapseField: 'Collapse Field', showButtons: 'Show +/- Buttons', hideButtons: 'Hide +/- Buttons',
    sum: 'Sum', count: 'Count', countNumbers: 'Count Numbers', average: 'Average', min: 'Min', max: 'Max', product: 'Product', stdev: 'StdDev', stdevp: 'StdDevP', variance: 'Var', variancep: 'VarP', distinctCount: 'Distinct Count', rowLabels: 'Row Labels', grandTotal: 'Grand Total', loadingPivot: 'Loading PivotTable', pivotCollision: 'PivotTable cannot expand', pivotRefreshFailed: 'PivotTable refresh failed', pivotRefreshRequired: 'Pivot refresh required', invalidSource: 'Select a valid PivotTable source', invalidDestination: 'Enter a valid destination such as A1', layoutUpdated: 'PivotTable layout updated', filterUpdated: 'Pivot filter updated', currentRegion: 'Current region', tableSource: 'Table', namedRange: 'Defined name', allItems: 'All', selectedItems: '{count} selected', excludedItems: '{count} excluded', topItemsSummary: '{direction} {count} by {field}', labelFilter: 'Label Filters', dateFilter: 'Date Filters', valueFilter: 'Value Filters', beginsWith: 'Begins With', notBeginsWith: 'Does Not Begin With', endsWith: 'Ends With', notEndsWith: 'Does Not End With', contains: 'Contains', notContains: 'Does Not Contain', between: 'Between', notBetween: 'Not Between', before: 'Before', after: 'After', top: 'Top', bottom: 'Bottom', dynamicDate: 'Dynamic date', today: 'Today', yesterday: 'Yesterday', tomorrow: 'Tomorrow', thisWeek: 'This Week', lastWeek: 'Last Week', nextWeek: 'Next Week', thisMonth: 'This Month', lastMonth: 'Last Month', nextMonth: 'Next Month', thisQuarter: 'This Quarter', lastQuarter: 'Last Quarter', nextQuarter: 'Next Quarter', thisYear: 'This Year', lastYear: 'Last Year', nextYear: 'Next Year', yearToDate: 'Year to Date', otherSortOptions: 'More Sort Options…', clearFieldFilter: 'Clear Filter From “{field}”', sortField: 'Sort by', pivotOptions: 'PivotTable Options', layoutFormat: 'Layout & Format', displayOptions: 'Display', fillEmptyCells: 'Fill empty cells', emptyCellText: 'For empty cells show', showErrorValues: 'For error values show', errorCellText: 'Error display text', showFieldHeaders: 'Show field captions and filter buttons', autoFitColumns: 'Autofit column widths on update', preserveFormatting: 'Preserve cell formatting on update',
    topBottomFilter: 'Top/Bottom Filter', topBottomMode: 'Filter by', items: 'Items', percent: 'Percent', threshold: 'Threshold', topBottomSummary: '{direction} {mode} {threshold} by {field}',
    timelineLevel: 'Timeline level', timelineStyle: 'Timeline style', timelineCaption: 'Timeline caption', timelinePrevious: 'Previous period', timelineNext: 'Next period', timelineAllPeriods: 'All periods', timelineHeader: 'Show header', timelineSelection: 'Show selection', reportConnections: 'Report Connections', noCompatiblePivots: 'No compatible PivotTables',
  },
} as const;

export type PivotMessageKey = keyof typeof messages['en-US'];
export function pivotText(locale: Locale, key: PivotMessageKey): string { return messages[locale][key]; }
export function pivotDefinedNameScopeText(locale: Locale, scope: 'workbook' | 'sheet', sheetName?: string): string {
  if (scope === 'workbook') return locale === 'zh-CN' ? '工作簿' : 'Workbook';
  const label = locale === 'zh-CN' ? '工作表' : 'Worksheet';
  return `${label}: ${sheetName ?? ''}`.trim();
}
export function pivotTemplate(locale: Locale, key: PivotMessageKey, values: Record<string, string | number>): string {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), pivotText(locale, key));
}
