import type { Locale } from '../../i18n';

const messages = {
  'zh-CN': {
    createTitle: '创建数据透视表', chooseData: '请选择要分析的数据', chooseLocation: '选择放置数据透视表的位置', newWorksheet: '新工作表', existingWorksheet: '现有工作表', confirm: '确定', cancel: '取消',
    fieldsTitle: '数据透视表字段', addFields: '选择要添加到报表的字段', search: '搜索', total: '合计', dragFields: '在以下区域拖动字段:', filters: '筛选', columns: '列', rows: '行', values: '值', delayUpdate: '延迟布局更新', update: '更新', view: '视图',
    noFields: '没有可用字段', noMatches: '没有匹配字段', loading: '正在准备数据透视表字段。', error: '数据透视表字段加载失败。', empty: '请选择一个数据透视表以配置字段。', close: '关闭数据透视表字段', source: '数据源', target: '目标', configure: '配置', refresh: '刷新', compact: '紧凑', outline: '大纲', tabular: '表格', controlField: '控件字段', slicer: '切片器', timeline: '时间线', pivotChart: '数据透视图',
    expandFields: '展开字段', collapseFields: '折叠字段', fieldMenu: '字段菜单', moveUp: '上移', moveDown: '下移', remove: '删除', advancedFields: '高级数据透视表字段',
    valueSettings: '值字段设置', summaryFunction: '汇总方式', displayName: '自定义名称', displayNamePlaceholder: '输入自定义名称', numberFormat: '数字格式', numberFormatPlaceholder: '数字格式，例如 #,##0.00', showValueAs: '值显示方式', baseField: '基本字段', baseItem: '基本项',
    normal: '无计算', grandPercent: '总计的百分比', rowPercent: '行汇总的百分比', columnPercent: '列汇总的百分比', parentPercent: '父级汇总的百分比', differenceFrom: '差异', percentDifferenceFrom: '差异百分比', runningTotal: '按某一字段汇总', rank: '升序/降序排列', index: '指数',
    sortBy: '排序', ascending: '升序', descending: '降序', valueAscending: '按值升序', valueDescending: '按值降序', clearSort: '清除排序', filterValues: '筛选值', filterMode: '筛选模式', showAll: '显示全部', includeSelected: '仅包含所选项', excludeSelected: '排除所选项',
    groupBy: '分组', years: '年', quarters: '季度', months: '月', weeks: '周', days: '日', clearGroup: '取消组合', groupNumbers: '数字分组', by10: '间隔 10', by100: '间隔 100', groupAll: '组合全部值', groupOne: '组 1',
    calculatedFieldsItems: '计算字段和计算项', calculatedField: '计算字段', calculatedItem: '计算项', calculatedName: '名称', calculatedFormula: '公式', calculatedItemName: '计算项名称', add: '添加',
    slicerTitle: '切片器', clearFilter: '清除筛选', selectAll: '全选', searchItems: '搜索项目', timelineTitle: '时间线', timelineStart: '开始日期', timelineEnd: '结束日期', clearTimeline: '清除时间线', configurationActions: '数据透视表配置操作',
    sum: '求和', count: '计数', countNumbers: '数值计数', average: '平均值', min: '最小值', max: '最大值', product: '乘积', stdev: '标准偏差', stdevp: '总体标准偏差', variance: '方差', variancep: '总体方差', distinctCount: '非重复值计数', rowLabels: '行标签', grandTotal: '总计', loadingPivot: '正在加载数据透视表', pivotCollision: '数据透视表无法展开', pivotRefreshFailed: '数据透视表刷新失败', pivotRefreshRequired: '数据透视表需要刷新', invalidSource: '请选择有效的数据透视表数据源', invalidDestination: '请输入有效的放置位置，例如 A1', layoutUpdated: '数据透视表布局已更新', filterUpdated: '数据透视表筛选已更新', currentRegion: '当前区域', tableSource: '表格', namedRange: '定义名称', allItems: '全部', selectedItems: '已选择 {count} 项', labelFilter: '标签筛选', valueFilter: '值筛选', otherSortOptions: '其他排序选项…', clearFieldFilter: '从“{field}”中清除筛选', sortField: '排序依据',
  },
  'en-US': {
    createTitle: 'Create PivotTable', chooseData: 'Choose the data that you want to analyze', chooseLocation: 'Choose where you want the PivotTable to be placed', newWorksheet: 'New Worksheet', existingWorksheet: 'Existing Worksheet', confirm: 'OK', cancel: 'Cancel',
    fieldsTitle: 'PivotTable Fields', addFields: 'Choose fields to add to report', search: 'Search', total: 'Total', dragFields: 'Drag fields between areas below:', filters: 'Filters', columns: 'Columns', rows: 'Rows', values: 'Values', delayUpdate: 'Defer Layout Update', update: 'Update', view: 'View',
    noFields: 'No fields are available', noMatches: 'No matching fields', loading: 'Preparing PivotTable fields.', error: 'PivotTable fields could not be loaded.', empty: 'Select a PivotTable to configure its fields.', close: 'Close PivotTable fields', source: 'Source', target: 'Target', configure: 'Configure', refresh: 'Refresh', compact: 'Compact', outline: 'Outline', tabular: 'Tabular', controlField: 'Control field', slicer: 'Slicer', timeline: 'Timeline', pivotChart: 'Pivot Chart',
    expandFields: 'Expand fields', collapseFields: 'Collapse fields', fieldMenu: 'Field menu', moveUp: 'Move up', moveDown: 'Move down', remove: 'Remove', advancedFields: 'Advanced PivotTable fields',
    valueSettings: 'Value Field Settings', summaryFunction: 'Summarize Values By', displayName: 'Custom Name', displayNamePlaceholder: 'Custom display name', numberFormat: 'Number Format', numberFormatPlaceholder: 'Number format, e.g. #,##0.00', showValueAs: 'Show Values As', baseField: 'Base field', baseItem: 'Base item',
    normal: 'No Calculation', grandPercent: '% of Grand Total', rowPercent: '% of Row Total', columnPercent: '% of Column Total', parentPercent: '% of Parent Total', differenceFrom: 'Difference From', percentDifferenceFrom: '% Difference From', runningTotal: 'Running Total In', rank: 'Rank', index: 'Index',
    sortBy: 'Sort', ascending: 'Ascending', descending: 'Descending', valueAscending: 'Value ascending', valueDescending: 'Value descending', clearSort: 'Clear sort', filterValues: 'Filter values', filterMode: 'Filter mode', showAll: 'Show all', includeSelected: 'Include selected', excludeSelected: 'Exclude selected',
    groupBy: 'Group by', years: 'Years', quarters: 'Quarters', months: 'Months', weeks: 'Weeks', days: 'Days', clearGroup: 'Ungroup', groupNumbers: 'Group numbers', by10: 'By 10', by100: 'By 100', groupAll: 'Group all values', groupOne: 'Group 1',
    calculatedFieldsItems: 'Calculated Fields / Items', calculatedField: 'Calculated field', calculatedItem: 'Calculated item', calculatedName: 'Name', calculatedFormula: 'Formula', calculatedItemName: 'Item name', add: 'Add',
    slicerTitle: 'Slicer', clearFilter: 'Clear filter', selectAll: 'Select all', searchItems: 'Search items', timelineTitle: 'Timeline', timelineStart: 'Timeline start', timelineEnd: 'Timeline end', clearTimeline: 'Clear timeline', configurationActions: 'Pivot configuration actions',
    sum: 'Sum', count: 'Count', countNumbers: 'Count Numbers', average: 'Average', min: 'Min', max: 'Max', product: 'Product', stdev: 'StdDev', stdevp: 'StdDevP', variance: 'Var', variancep: 'VarP', distinctCount: 'Distinct Count', rowLabels: 'Row Labels', grandTotal: 'Grand Total', loadingPivot: 'Loading PivotTable', pivotCollision: 'PivotTable cannot expand', pivotRefreshFailed: 'PivotTable refresh failed', pivotRefreshRequired: 'PivotTable refresh required', invalidSource: 'Select a valid PivotTable source', invalidDestination: 'Enter a valid destination such as A1', layoutUpdated: 'PivotTable layout updated', filterUpdated: 'PivotTable filter updated', currentRegion: 'Current region', tableSource: 'Table', namedRange: 'Defined name', allItems: 'All', selectedItems: '{count} selected', labelFilter: 'Label Filters', valueFilter: 'Value Filters', otherSortOptions: 'More Sort Options…', clearFieldFilter: 'Clear Filter From “{field}”', sortField: 'Sort by',
  },
} as const;

export type PivotMessageKey = keyof typeof messages['en-US'];
export function pivotText(locale: Locale, key: PivotMessageKey): string { return messages[locale][key]; }
export function pivotTemplate(locale: Locale, key: PivotMessageKey, values: Record<string, string | number>): string {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), pivotText(locale, key));
}
